[package]
name = "gamma"
version = "0.1.0"
authors = ["toteload"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros = "0.24.3"
