[package]
name = "gamma_zero"
version = "0.1.0"
authors = ["toteload"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jello = { path = "../jello" }
