[env]
#LLVM_SYS_150_PREFIX = { value = "/Users/davidbos/code/clang+llvm-17.0.6-arm64-apple-darwin22.0", force = true }
#LLVM_SYS_150_PREFIX = { value = "F:/david/code/LLVM/MinSizeRel-15.0.7/", force = true }
